GET https://bb53-80-94-27-69.ngrok-free.app/send?deviceId=dtv6HwU4Sp2EarRIZYat9R:APA91bHgq6MCOV_CBBVsEDwGCMqI3jBKoq-npJTGUWN_NTd5BP55YFPvO6up5vQeYw8PWUqgx_dZr6kn4fiCHerqNH9-5Prn8qz9xP4RyaXo3ay3SwX2FsY&title=Hi&body=body

###

GET https://bb53-80-94-27-69.ngrok-free.app/confirm
